name: keuangan_baru
description: A new Flutter project for financial management.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1 # Pastikan versi ini
  onesignal_flutter: ^5.0.0 # Pastikan versi ini
  flutter_local_notifications: ^17.1.2 # Pastikan versi ini
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  csv: ^5.1.1
  open_filex: ^4.3.4
  image_picker: ^1.1.2
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/
